### ISSUE TITLE
Repository Browsing

### ISSUE THREAD

**Issue by fmcc** [SChAth/Editor#13]
The editor should have a means to navigate the various project repositories, as well as browse the contents of a repository. I'm assuming the current flat repository structure will be maintained (i.e. no subdirectories within a repository). 

So for a given repository a page will provide a list of all XML files within that repository, each linking to the edit page for that XML file. It seems to me that the entries in this list should display the following data fields:
- Filename
- Current status in the git repository 
- Validity of XML (I've come across some that I can't parse). 

While these will be consistent across all repositories, it seems to me that there will be additional pieces of data that should be extracted from the XML and displayed in the listing which are dependent on the document type. These can both serve to display what the file contains, as well as give some indication of the level of editing required for the file. There will then be a couple of types of customisable data fields that can be implemented for particular file types:
- A data field that displays the contents of a node from a provided XPath. 
- A data field that displays whether or not there is content at all provided XPaths.

**Comment by PietroLiuzzo** [comment]
There are indeed many (most!) records which are not valid at the moment as they have been converted from legacy data. It would be nice to see the title of the file for place records, as the filename does not give a lot of information on the record itself.  for works and manuscripts there will be also ids (in idno).

for places it would be nice to see //place/@type content and if there is anything at //location/geo, which should contain coordinates.
